Repository nathanmarlor/foxess_modbus, pull requests merged in 2023-04, with the labels that each got.

#126 Move to actual inverter totals rather than integration sensors for AC1
  custom_components/foxess_modbus/entities/xx1_aux_entity_descriptions.py
Labels: refactoring

#153 Fix issues around modbus TCP connections/reconnections
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/modbus_client.py
  custom_components/foxess_modbus/modbus_controller.py
Labels: bug

#156 Removed version
  custom_components/foxess_modbus/const.py
Labels: removal

#148 Abort a refresh if the previous refresh is still in progress
  custom_components/foxess_modbus/modbus_client.py
  custom_components/foxess_modbus/modbus_controller.py
Labels: bug

#138 Ensure friendly names are valid in entity ids
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/translations/en.json
Labels: bug
