Repository nathanmarlor/foxess_modbus, pull requests merged in 2023-03, with the labels that each got.

#12 Added max SoC sensor for AUX
  custom_components/foxess_modbus/sensors/h1_aux_sensors.py
Labels: enhancement

#13 Added configurable slave ID
  README.md
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/const.py
  custom_components/foxess_modbus/modbus_client.py
  custom_components/foxess_modbus/translations/en.json
  images/setup.png
Labels: enhancement

#14 Added support for multiple inverters
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/const.py
  custom_components/foxess_modbus/sensor.py
  custom_components/foxess_modbus/sensors/h1_aux_sensors.py
  custom_components/foxess_modbus/sensors/h1_lan_sensors.py
  custom_components/foxess_modbus/sensors/modbus_sensor.py
  custom_components/foxess_modbus/translations/en.json
Labels: enhancement

#15 Reduced AUX max reads to improve stability
  custom_components/foxess_modbus/modbus_controller.py
Labels: bug

#18 Added EPS Voltage, Total Watthours and CT2
  custom_components/foxess_modbus/modbus_controller.py
  custom_components/foxess_modbus/sensors/h1_aux_sensors.py
Labels: enhancement

#19 Renamed sensors to match ModbusUSB/LAN
  custom_components/foxess_modbus/sensors/h1_aux_sensors.py
  custom_components/foxess_modbus/sensors/h1_lan_sensors.py
Labels: bug

#20 Added binary sensor domain for charge enabled flags
  custom_components/foxess_modbus/binary_sensor.py
  custom_components/foxess_modbus/sensors/h1_aux_binary_sensors.py
Labels: enhancement

#21 Ensured binary sensors are HA compliant
  custom_components/foxess_modbus/sensors/h1_aux_binary_sensors.py
Labels: enhancement

#24 Added HA write register service
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/modbus_client.py
  custom_components/foxess_modbus/modbus_controller.py
  custom_components/foxess_modbus/sensors/modbus_sensor.py
  custom_components/foxess_modbus/services.yaml
Labels: enhancement

#25 Updated mechanism to have multiple instances
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/binary_sensor.py
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/const.py
  custom_components/foxess_modbus/modbus_client.py
  custom_components/foxess_modbus/modbus_controller.py
  custom_components/foxess_modbus/modbus_serial_client.py
  custom_components/foxess_modbus/modbus_tcp_client.py
  custom_components/foxess_modbus/sensor.py
  custom_components/foxess_modbus/sensors/h1_aux_binary_sensors.py
  custom_components/foxess_modbus/sensors/h1_aux_sensors.py
  custom_components/foxess_modbus/sensors/h1_lan_sensors.py
  custom_components/foxess_modbus/sensors/modbus_sensor.py
  custom_components/foxess_modbus/translations/en.json
Labels: enhancement

#28 Ensured modbus client is thread safe
  custom_components/foxess_modbus/modbus_client.py
Labels: bug

#29 Added friendly name to descriptions if set
  custom_components/foxess_modbus/sensors/modbus_sensor.py
Labels: enhancement

#31 Improved reconnect after client hang up
  custom_components/foxess_modbus/modbus_controller.py
Labels: enhancement

#32 Group host and port together for simpliicity
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/config_flow.py
Labels: refactoring

#33 Added check to prevent duplicate hosts/friendly names
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/translations/en.json
Labels: enhancement

#34 Added friendly name to write service
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/modbus_controller.py
  custom_components/foxess_modbus/services.yaml
Labels: enhancement

#35 Reject unsupported model types with error
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/modbus_controller.py
  custom_components/foxess_modbus/translations/en.json
Labels: enhancement

#36 Updated sensor to include state class
  custom_components/foxess_modbus/sensors/modbus_sensor.py
Labels: bug

#37 Fix unexpected type when calling service with jinja2 template
  custom_components/foxess_modbus/__init__.py
Labels: bug

#39 Revert to using sync libraries to mirror native HA
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/const.py
  custom_components/foxess_modbus/modbus_client.py
  custom_components/foxess_modbus/modbus_controller.py
  custom_components/foxess_modbus/modbus_serial_client.py
  custom_components/foxess_modbus/modbus_tcp_client.py
  custom_components/foxess_modbus/sensors/h1_aux_sensors.py
Labels: refactoring

#48 Added AC1 and AIO H1 support
  custom_components/foxess_modbus/binary_sensor.py
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/const.py
  custom_components/foxess_modbus/entities/h1_aux_binary_sensors.py
  custom_components/foxess_modbus/entities/h1_aux_selects.py
  custom_components/foxess_modbus/entities/xx1_aux_binary_sensors.py
  custom_components/foxess_modbus/entities/xx1_aux_numbers.py
  custom_components/foxess_modbus/entities/xx1_aux_selects.py
  custom_components/foxess_modbus/entities/xx1_aux_sensors.py
  custom_components/foxess_modbus/entities/xx1_lan_sensors.py
  custom_components/foxess_modbus/modbus_controller.py
  custom_components/foxess_modbus/number.py
  custom_components/foxess_modbus/select.py
  custom_components/foxess_modbus/sensor.py
Labels: enhancement

#49 Added poll rate and max read to options flow
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/const.py
  custom_components/foxess_modbus/modbus_controller.py
  custom_components/foxess_modbus/translations/en.json
Labels: enhancement

#52 Be smarter about which sensors to notify after a poll
  custom_components/foxess_modbus/common/callback_controller.py
  custom_components/foxess_modbus/entities/modbus_entity_mixin.py
  custom_components/foxess_modbus/entities/modbus_number.py
  custom_components/foxess_modbus/entities/modbus_select.py
  custom_components/foxess_modbus/modbus_controller.py
Labels: performance

#55 Be smarter about grouping address into read commands
  custom_components/foxess_modbus/inverter_profiles.py
  custom_components/foxess_modbus/modbus_client.py
  custom_components/foxess_modbus/modbus_controller.py
Labels: performance

#64 Corrected BMS kWh description
  custom_components/foxess_modbus/entities/xx1_aux_sensors.py
Labels: bug

#67 Fixed config flow not returning errors when adding a second inverter
  custom_components/foxess_modbus/config_flow.py
Labels: bug

#68 Swapped ambient/inverter temperature to match Fox Cloud
  custom_components/foxess_modbus/entities/xx1_aux_sensors.py
Labels: bug

#76 Add CT2 to H1/AC1 LAN
  custom_components/foxess_modbus/entities/xx1_lan_sensors.py
Labels: enhancement

#79 Added battery charge/discharge sensors
  custom_components/foxess_modbus/entities/xx1_aux_sensors.py
Labels: enhancement

#80 Fix detecting duplicates for TCP/SERIAL
  custom_components/foxess_modbus/config_flow.py
Labels: bug

#81 Renamed battery charge/discharge to be consistent
  custom_components/foxess_modbus/entities/xx1_aux_sensors.py
Labels: bug

#89 Fix handling unavailable values in modbus_charge_period_sensors
  custom_components/foxess_modbus/entities/modbus_charge_period_sensors.py
Labels: bug

#91 Added validation for AUX inverter types
  custom_components/foxess_modbus/entities/modbus_binary_sensor.py
  custom_components/foxess_modbus/entities/modbus_charge_period_config.py
  custom_components/foxess_modbus/entities/modbus_charge_period_sensors.py
  custom_components/foxess_modbus/entities/modbus_entity_mixin.py
  custom_components/foxess_modbus/entities/modbus_number.py
  custom_components/foxess_modbus/entities/modbus_select.py
  custom_components/foxess_modbus/entities/modbus_sensor.py
  custom_components/foxess_modbus/entities/validation.py
  custom_components/foxess_modbus/entities/xx1_aux_entity_descriptions.py
Labels: enhancement

#92 Added validation for LAN inverter types
  custom_components/foxess_modbus/entities/xx1_lan_entity_descriptions.py
Labels: enhancement

#96 Fixed config flow not resetting on failure to connect
  custom_components/foxess_modbus/config_flow.py
Labels: bug

#97 Fixed required friendly name in service calls
  custom_components/foxess_modbus/__init__.py
  custom_components/foxess_modbus/services.yaml
Labels: bug

#98 Added integration sensors to replace manually configured yaml
  custom_components/foxess_modbus/entities/modbus_integration_sensor.py
  custom_components/foxess_modbus/entities/xx1_aux_entity_descriptions.py
  custom_components/foxess_modbus/entities/xx1_lan_entity_descriptions.py
  custom_components/foxess_modbus/inverter_profiles.py
  custom_components/foxess_modbus/manifest.json
Labels: enhancement

#99 Fixed validation for grid consumption total
  custom_components/foxess_modbus/entities/xx1_aux_entity_descriptions.py
Labels: bug

#100 Added differentiation between signed/unsigned numbers
  custom_components/foxess_modbus/entities/modbus_sensor.py
  custom_components/foxess_modbus/entities/xx1_aux_entity_descriptions.py
  custom_components/foxess_modbus/modbus_client.py
Labels: bug

#101 Rationalised inverter/inverter battery sensors
  custom_components/foxess_modbus/entities/xx1_aux_entity_descriptions.py
Labels: enhancement

#94 Automatically configure energy dashboard through config flow
  .vscode/launch.json
  custom_components/foxess_modbus/config_flow.py
  custom_components/foxess_modbus/const.py
  custom_components/foxess_modbus/manifest.json
  custom_components/foxess_modbus/translations/en.json
Labels: enhancement
